##NBA Multi-Dimensional Analytics & Scouting Engine

A data pipeline and analytics framework for integrating NBA tracking, synergy, box score, and shot data into a unified player-level dataset.

**Key Features**

Multi-source data integration (tracking, synergy, box score, shot locations)
Centralized master dataset with 500+ engineered features
Regular season vs playoff comparison for contextual analysis
Modular ingestion pipeline with caching (Parquet-based)
Built for downstream modeling (e.g., RAPM, salary prediction)

# Import Packages

In [40]:
pip install shap

Defaulting to user installation because normal site-packages is not writeable
Collecting shap
  Downloading shap-0.49.1-cp39-cp39-macosx_10_9_x86_64.whl.metadata (25 kB)
Requirement already satisfied: numpy in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from shap) (2.0.2)
Requirement already satisfied: scipy in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from shap) (1.13.1)
Requirement already satisfied: scikit-learn in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from shap) (1.6.1)
Requirement already satisfied: pandas in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from shap) (2.3.3)
Requirement already satisfied: tqdm>=4.27.0 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from shap) (4.68.3)
Requirement already satisfied: packaging>20.9 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from shap) (26.2)
Collecting slicer==0.0.8 (from shap)
  Downloading slicer-0.0.8-py3-none-any.whl.metadata (4.0 kB)
Collecting numba>=0.54 (from shap)
  Downloading numba-0.60.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (2.7 kB)
Collecting cloudpickle (from shap)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from shap) (4.15.0)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba>=0.54->shap)
  Downloading llvmlite-0.43.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from pandas->shap) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from pandas->shap) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.15.0)
Requirement already satisfied: joblib>=1.2.0 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from scikit-learn->shap) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from scikit-learn->shap) (3.6.0)
Downloading shap-0.49.1-cp39-cp39-macosx_10_9_x86_64.whl (559 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.2/559.2 kB 3.9 MB/s  0:00:00
Downloading slicer-0.0.8-py3-none-any.whl (15 kB)
Downloading numba-0.60.0-cp39-cp39-macosx_10_9_x86_64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 17.2 MB/s  0:00:00
Downloading llvmlite-0.43.0-cp39-cp39-macosx_10_9_x86_64.whl (31.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.1/31.1 MB 32.7 MB/s  0:00:00 eta 0:00:01
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Installing collected packages: slicer, llvmlite, cloudpickle, numba, shap
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [shap][32m4/5 [shap]]te]
Successfully installed cloudpickle-3.1.2 llvmlite-0.43.0 numba-0.60.0 shap-0.49.1 slicer-0.0.8
Note: you may need to restart the kernel to use updated packages.

In [125]:
# Standard library
import gc
import itertools
import pickle
import time
import warnings
from functools import reduce
from random import sample
from unidecode import unidecode
import re, requests
from pathlib import Path
import sklearn
import shap
import joblib
import json

# Core scientific stack
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from matplotlib.offsetbox import AnnotationBbox, OffsetImage
from matplotlib.patches import Rectangle
from matplotlib.ticker import FormatStrFormatter
import seaborn as sns
import lightgbm as lgb
from sklearn.metrics import r2_score, mean_absolute_error

import holoviews as hv
import hvplot.pandas  # noqa: F401 (registers hvplot accessor)
hv.extension("bokeh")

# Stats
from scipy import stats

# NBA API
from nba_api.stats.static.teams import get_teams
from nba_api.stats.static.players import get_players, get_active_players
from nba_api.stats.endpoints import leaguegamefinder, leaguedashplayerstats

import importlib
import nba_viz_utils
importlib.reload(nba_viz_utils)


from nba_viz_utils import *

In [2]:
pwd

'/Users/siddharthravindran/Documents/nba_data_vis'

# Upload Master

## Load Master Data Frame

In [3]:
df_master = pd.read_parquet(
  "data/df_master_current.parquet"
).set_index(INDEX_COLS).sort_index()

## Master Integrity Check

In [4]:
check_master_integrity(df_master)

📊 Integrity Check for df_master:
  - Shape: (8373, 730)
  - Total Players: 1556
  - Seasons Present: ['2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25', '2025-26']
  - ✅ No duplicate indices found.
  - ✅ All columns contain at least some data.

# Missing Data Check

In [4]:
nan_by_season = df_master.groupby(level='SEASON').apply(lambda g: g.isna().mean())
flip = nan_by_season.columns[(nan_by_season.max() > 0.95) & (nan_by_season.min() < 0.5)]
nan_by_season[flip].round(2)

Empty DataFrame
Columns: []
Index: [2015-16, 2016-17, 2017-18, 2018-19, 2019-20, 2020-21, 2021-22, 2022-23, 2023-24, 2024-25, 2025-26]

# Transpose Regular Season & Playoffs

In [5]:
model = build_model_table(df_master)

In [6]:
model

,PLAYER_ID,SEASON,PLAYER_NAME,TEAM_ABBREVIATION,TEAM_ID,GP_rs,W_rs,L_rs,W_PCT_rs,MIN_rs,...,CLUTCH_TS_PCT_po,CLUTCH_USG_PCT_po,CLUTCH_E_PACE_po,CLUTCH_PACE_po,CLUTCH_PACE_PER40_po,CLUTCH_PIE_po,CLUTCH_POSS_po,CLUTCH_FGM_PG_po,CLUTCH_FGA_PG_po,made_playoffs
0,201950,2019-20,Jrue Holiday,NOP,1610612740,61,26,35,0.426,34.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1627759,2019-20,Jaylen Brown,BOS,1610612738,57,38,19,0.667,33.9,...,0.444,0.186,94.69,94.03,78.36,0.118,100.0,0.5,1.5,1
2,203935,2019-20,Marcus Smart,BOS,1610612738,60,39,21,0.650,32.0,...,0.429,0.116,93.94,92.74,77.28,0.063,96.0,0.2,0.6,1
3,1628970,2019-20,Miles Bridges,CHA,1610612766,65,23,42,0.354,30.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,202710,2019-20,Jimmy Butler III,MIA,1610612748,58,38,20,0.655,33.8,...,0.760,0.342,88.07,87.53,72.94,0.341,96.0,0.9,1.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5963,204066,2018-19,John Holland,CLE,1610612739,1,0,1,0.000,0.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5964,1629122,2019-20,J.P. Macura,CLE,1610612739,1,1,0,1.000,0.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5965,1630701,2022-23,Michael Foster Jr.,PHI,1610612755,1,1,0,1.000,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5966,1628382,2023-24,Justin Jackson,MIN,1610612750,2,2,0,1.000,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5967,1627755,2018-19,Tyler Ulis,CHI,1610612741,1,0,1,0.000,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [7]:
m = model.reset_index()
m['PLAYER_NAME'] = m['PLAYER_NAME'].apply(norm_name)
print("dupe player-seasons:", m.duplicated(subset=['PLAYER_ID','SEASON']).sum())

dupe player-seasons: 0

In [10]:
# m.to_parquet("data/transposed_df_master.parquet")

model = pd.read_parquet("data/transposed_df_master.parquet")

In [11]:
model

,index,PLAYER_ID,SEASON,PLAYER_NAME,TEAM_ABBREVIATION,TEAM_ID,GP_rs,W_rs,L_rs,W_PCT_rs,...,CLUTCH_TS_PCT_po,CLUTCH_USG_PCT_po,CLUTCH_E_PACE_po,CLUTCH_PACE_po,CLUTCH_PACE_PER40_po,CLUTCH_PIE_po,CLUTCH_POSS_po,CLUTCH_FGM_PG_po,CLUTCH_FGA_PG_po,made_playoffs
0,0,201950,2019-20,jrue holiday,NOP,1610612740,61,26,35,0.426,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,1627759,2019-20,jaylen brown,BOS,1610612738,57,38,19,0.667,...,0.444,0.186,94.69,94.03,78.36,0.118,100.0,0.5,1.5,1
2,2,203935,2019-20,marcus smart,BOS,1610612738,60,39,21,0.650,...,0.429,0.116,93.94,92.74,77.28,0.063,96.0,0.2,0.6,1
3,3,1628970,2019-20,miles bridges,CHA,1610612766,65,23,42,0.354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,202710,2019-20,jimmy butler,MIA,1610612748,58,38,20,0.655,...,0.760,0.342,88.07,87.53,72.94,0.341,96.0,0.9,1.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5963,5963,204066,2018-19,john holland,CLE,1610612739,1,0,1,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5964,5964,1629122,2019-20,jp macura,CLE,1610612739,1,1,0,1.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5965,5965,1630701,2022-23,michael foster,PHI,1610612755,1,1,0,1.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5966,5966,1628382,2023-24,justin jackson,MIN,1610612750,2,2,0,1.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5967,5967,1627755,2018-19,tyler ulis,CHI,1610612741,1,0,1,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

# Salaries

In [ ]:
all_urls = harvest_player_urls()        # all 11 seasons → ~1,800 unique players
salaries  = scrape_all(all_urls)
print(salaries.shape); salaries.head()

  2015-16: 487 players (total unique 487)
  2016-17: 494 players (total unique 586)
  2017-18: 549 players (total unique 722)
  2018-19: 537 players (total unique 830)
  2019-20: 538 players (total unique 949)
  2020-21: 547 players (total unique 1043)
  2021-22: 613 players (total unique 1170)
  2022-23: 548 players (total unique 1255)
  2023-24: 578 players (total unique 1355)
  2024-25: 575 players (total unique 1459)
  2025-26: 588 players (total unique 1562)
  50/1562
  100/1562
  150/1562
  200/1562
  250/1562
  300/1562
  350/1562
  400/1562
  450/1562
  500/1562
  550/1562
  600/1562
  650/1562
  700/1562
  750/1562
  800/1562
  850/1562
  900/1562
  950/1562
  1000/1562
  1050/1562
  1100/1562
  1150/1562
  1200/1562
  1250/1562
  1300/1562
  1350/1562
  1400/1562
  1450/1562
  1500/1562
  1550/1562
(7701, 4)

    SEASON   Salary            Player          name_key
0  2016-17  5994764      Álex Abrines      alex abrines
1  2017-18  5725000      Álex Abrines      alex abrines
2  2018-19  3575183      Álex Abrines      alex abrines
3  2020-21  2582160  Precious Achiuwa  precious achiuwa
4  2021-22  2711280  Precious Achiuwa  precious achiuwa

In [6]:
# salaries.to_csv(DATA_DIR / "bbref_salaries_2015-2025.csv", index=False)

salaries = pd.read_csv("data/bbref_salaries_2015-2025.csv")
salaries = salaries[salaries['SEASON'].between('2015-16', '2024-25')].reset_index(drop=True)

In [7]:
salaries_25_26 = pd.read_csv("data/contracts.csv")

In [ ]:
col_2526 = next(c for c in salaries_25_26.columns if '2025' in str(c))   # column NAME → separate var

def to_int_salary(s):
    digits = re.sub(r'[^0-9]', '', str(s).split('.')[0])   # split('.') guards against a float '45780966.0'
    return int(digits) if digits else 0

current = salaries_25_26[['Player', col_2526]].dropna().copy()
current['Salary']   = current[col_2526].map(to_int_salary)
current = current[current['Salary'] > 0]
current['SEASON']   = '2025-26'
current['name_key'] = current['Player'].apply(norm_name)
current = current[['SEASON', 'Salary', 'Player', 'name_key']]
print(current.shape); current.head()

(529, 4)

    SEASON    Salary         Player       name_key
0  2025-26  59606817  Stephen Curry  stephen curry
1  2025-26  55224526    Joel Embiid    joel embiid
2  2025-26  55224526   Nikola Jokić   nikola jokic
3  2025-26  54708609   Kevin Durant   kevin durant
4  2025-26  54126450   Jayson Tatum   jayson tatum

In [32]:
salaries = pd.concat([salaries, current[['SEASON', 'Salary', 'Player', 'name_key']]], ignore_index=True)
salaries = salaries.drop_duplicates(['name_key', 'SEASON'])

In [12]:
# salaries.to_csv("data/bbref_salaries_2015-2026.csv", index=False)
salaries = pd.read_csv("data/bbref_salaries_2015-2026.csv")

# Build Model Data Frame

In [13]:
model = attach_salaries(model, salaries)

In [14]:
# did the scrape actually fix the ~14% hole?
real = model[(model['GP_rs'] >= 20) & (model['MIN_rs'] >= 10)]
print(f"coverage (real-minute players): {real['Salary'].notna().mean():.1%}  "
      f"| missing rows: {real['Salary'].isna().sum()}")

coverage (real-minute players): 97.7%  | missing rows: 100

In [ ]:
# draft / experience — model-layer attributes, merged on PLAYER_ID
model['PLAYER_ID'] = model['PLAYER_ID'].astype(str)
bio = get_draft_table(SEASONS)
bio['PLAYER_ID'] = bio['PLAYER_ID'].astype(str)
model = (model.drop(columns=['DRAFT_POSITION', 'DRAFT_YR'], errors='ignore')   # idempotent
              .merge(bio, on='PLAYER_ID', how='left'))

model['IS_UNDRAFTED']     = model['DRAFT_POSITION'].isna().astype(int)
model['EXPERIENCE']       = (model['SEASON'].str[:4].astype(int) - model['DRAFT_YR']).clip(lower=0)
model['MAX_PCT_ELIGIBLE'] = model['EXPERIENCE'].map(
    lambda e: np.nan if pd.isna(e) else (0.25 if e <= 6 else 0.30 if e <= 9 else 0.35))

# target + filter LAST (so `model` stays the full scoreable population)
model['pct_cap'] = model['Salary'] / model['SEASON'].map(SALARY_CAP)

In [100]:
for nm in ['giannis', 'embiid']:
    sub = model[model['PLAYER_NAME'].str.contains(nm, case=False, na=False)]
    print(sub[['PLAYER_NAME','SEASON','ALLNBA_PRIOR3','ALLNBA_PRIOR_EVER']]
          .sort_values('SEASON').to_string(index=False), "\n")

# and the source table — how many selections did the parse actually capture for each?
print("Giannis in parsed All-NBA table:")
print(an[an['name_key'].str.contains('antetok', case=False, na=False)].sort_values('SEASON').to_string(index=False))
print("\nEmbiid in parsed All-NBA table:")
print(an[an['name_key'].str.contains('embiid', case=False, na=False)].sort_values('SEASON').to_string(index=False))

          PLAYER_NAME  SEASON  ALLNBA_PRIOR3  ALLNBA_PRIOR_EVER
giannis antetokounmpo 2015-16              0                  0
giannis antetokounmpo 2016-17              0                  0
 georgios papagiannis 2016-17              0                  0
giannis antetokounmpo 2017-18              1                  1
 georgios papagiannis 2017-18              0                  0
giannis antetokounmpo 2018-19              2                  2
giannis antetokounmpo 2019-20              3                  3
giannis antetokounmpo 2020-21              3                  4
giannis antetokounmpo 2021-22              3                  5
giannis antetokounmpo 2022-23              3                  6
giannis antetokounmpo 2023-24              3                  7
giannis antetokounmpo 2024-25              3                  8
giannis antetokounmpo 2025-26              3                  9

PLAYER_NAME  SEASON  ALLNBA_PRIOR3  ALLNBA_PRIOR_EVER
joel embiid 2016-17              0                  0
joel embiid 2017-18              0                  0
joel embiid 2018-19              1                  1
joel embiid 2019-20              2                  2
joel embiid 2020-21              2                  2
joel embiid 2021-22              2                  3
joel embiid 2022-23              2                  4
joel embiid 2023-24              3                  5
joel embiid 2024-25              2                  5
joel embiid 2025-26              1                  5

Giannis in parsed All-NBA table:
             name_key  SEASON  Tm   yr
giannis antetokounmpo 2016-17 2nd 2016
giannis antetokounmpo 2017-18 2nd 2017
giannis antetokounmpo 2018-19 1st 2018
giannis antetokounmpo 2019-20 1st 2019
giannis antetokounmpo 2020-21 1st 2020
giannis antetokounmpo 2021-22 1st 2021
giannis antetokounmpo 2022-23 1st 2022
giannis antetokounmpo 2023-24 1st 2023
giannis antetokounmpo 2024-25 1st 2024

Embiid in parsed All-NBA table:
   name_key  SEASON  Tm   yr
joel embiid 2017-18 2nd 2017
joel embiid 2018-19 2nd 2018
joel embiid 2020-21 2nd 2020
joel embiid 2021-22 2nd 2021
joel embiid 2022-23 1st 2022

In [ ]:
def fetch_all_nba_raw(url="https://www.basketball-reference.com/awards/all_league.html"):
    r = requests.get(url, headers=HDR, timeout=30)
    print("status:", r.status_code)
    soup = BeautifulSoup(r.content, "html.parser")
    for c in soup.find_all(string=lambda t: isinstance(t, Comment)):     # BBRef comment-hides tables
        if 'all_league' in c.lower() and '<table' in c.lower():
            soup.append(BeautifulSoup(c, "html.parser"))
    tbl = soup.find("table", id=re.compile("all.?league", re.I)) or soup.find("table")
    df = pd.read_html(StringIO(str(tbl)))[0]
    print("shape:", df.shape, "| cols:", list(df.columns))
    return df

allnba_raw = fetch_all_nba_raw()
allnba_raw.head(12)

In [59]:
# --- parse the raw All-NBA table → long (name_key, SEASON, team_level) ---
player_cols = ['Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']

an = allnba_raw[allnba_raw['Lg'] == 'NBA'].copy()          # drops blank rows + any ABA history
an = an.melt(id_vars=['Season', 'Tm'], value_vars=player_cols, value_name='player_raw')
an = an.dropna(subset=['player_raw'])

# strip the trailing position token(s): "Giannis Antetokounmpo F" / "... G-F" → name
an['player'] = an['player_raw'].str.replace(r'\s+[CFG](-[CFG])?$', '', regex=True)
an['name_key'] = an['player'].apply(norm_name)
an = an.rename(columns={'Season': 'SEASON'})
an = an[an['SEASON'].isin(SEASONS)][['name_key', 'SEASON', 'Tm']]
print("All-NBA selections parsed:", an.shape)
print(an.head())

# --- credential features: All-NBA in PRIOR seasons (causally clean + matches supermax rule) ---
an['yr'] = an['SEASON'].str[:4].astype(int)
picks = an.groupby(['name_key', 'yr']).size().rename('n').reset_index()   # 1 row per player-season selected

def prior_counts(name_key, year):
    p = picks[picks['name_key'] == name_key]
    last3 = int(p[(p['yr'] < year) & (p['yr'] >= year - 3)]['n'].sum())
    ever  = int(p[p['yr'] < year]['n'].sum())
    return last3, ever

model['name_key'] = model['PLAYER_NAME'].apply(norm_name)
yrs = model['SEASON'].str[:4].astype(int)
counts = [prior_counts(nk, y) for nk, y in zip(model['name_key'], yrs)]
model['ALLNBA_PRIOR3']     = [c[0] for c in counts]      # selections in trailing 3 seasons
model['ALLNBA_PRIOR_EVER'] = [c[1] for c in counts]      # career selections before this season
model = model.drop(columns='name_key')

print("\nplayers with ALLNBA_PRIOR3 > 0:", (model['ALLNBA_PRIOR3'] > 0).sum())
print(model[model['ALLNBA_PRIOR3'] > 0][['PLAYER_NAME','SEASON','ALLNBA_PRIOR3','ALLNBA_PRIOR_EVER','pct_cap']]
      .sort_values('ALLNBA_PRIOR_EVER', ascending=False).head(10))

All-NBA selections parsed: (165, 3)
       name_key   SEASON   Tm
0  nikola jokic  2025-26  1st
1  jaylen brown  2025-26  2nd
2   jalen duren  2025-26  3rd
3  nikola jokic  2024-25  1st
4   evan mobley  2024-25  2nd

players with ALLNBA_PRIOR3 > 0: 243
                PLAYER_NAME   SEASON  ALLNBA_PRIOR3  ALLNBA_PRIOR_EVER  \
140            lebron james  2025-26              3                 10
62             lebron james  2024-25              3                  9
756           stephen curry  2025-26              3                  9
1174  giannis antetokounmpo  2025-26              3                  9
628   giannis antetokounmpo  2024-25              3                  8
361           stephen curry  2024-25              3                  8
260            lebron james  2023-24              3                  8
1203  giannis antetokounmpo  2023-24              3                  7
371            nikola jokic  2025-26              3                  7
552           stephen curry  2023-24              3                  7

       pct_cap
140   0.340305
62    0.346607
756   0.385438
1174  0.350000
628   0.347026
361   0.396629
260   0.350000
1203  0.335537
371   0.357101
552   0.381674

In [101]:
# weight selection quality: 1st = 3, 2nd = 2, 3rd = 1
TM_WEIGHT = {'1st': 3, '2nd': 2, '3rd': 1}
an['weight'] = an['Tm'].map(TM_WEIGHT)

aw = an.dropna(subset=['weight']).copy()
aw['yr'] = aw['SEASON'].str[:4].astype(int)

# weighted credential: prior-ever and prior-3 in WEIGHTED points, not raw counts
def prior_weighted(name_key, year):
    p = aw[aw['name_key'] == name_key]
    ever  = int(p[p['yr'] <  year]['weight'].sum())
    last3 = int(p[(p['yr'] < year) & (p['yr'] >= year - 3)]['weight'].sum())
    return ever, last3

model['name_key'] = model['PLAYER_NAME'].apply(norm_name)
yrs = model['SEASON'].str[:4].astype(int)
wc = [prior_weighted(nk, y) for nk, y in zip(model['name_key'], yrs)]
model['ALLNBA_WT_EVER'] = [c[0] for c in wc]
model['ALLNBA_WT3']     = [c[1] for c in wc]
model = model.drop(columns='name_key')

# check the separation you care about
print(model[model['PLAYER_NAME'].str.contains('giannis|embiid', case=False, na=False)]
      [['PLAYER_NAME','SEASON','ALLNBA_WT_EVER','ALLNBA_WT3']]
      .query("SEASON == '2025-26'").to_string(index=False))

          PLAYER_NAME  SEASON  ALLNBA_WT_EVER  ALLNBA_WT3
          joel embiid 2025-26              11           3
giannis antetokounmpo 2025-26              25           9

In [103]:
print("seasons in model:", sorted(model['SEASON'].unique()))
print("PLAYER_ID dtype:", model['PLAYER_ID'].dtype, "| nulls:", model['PLAYER_ID'].isna().sum())
# a known multi-season guy should show one row per season, same ID
print(model[model['PLAYER_NAME'].str.contains('giannis antetokounmpo', case=False, na=False)]
      [['PLAYER_ID','SEASON','MIN_rs','FGM_rs']].sort_values('SEASON').to_string(index=False))

seasons in model: ['2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25', '2025-26']
PLAYER_ID dtype: object | nulls: 0
PLAYER_ID  SEASON  MIN_rs  FGM_rs
   203507 2015-16    35.3     6.4
   203507 2016-17    35.6     8.2
   203507 2017-18    36.7     9.9
   203507 2018-19    32.8    10.0
   203507 2019-20    30.4    10.9
   203507 2020-21    33.0    10.3
   203507 2021-22    32.9    10.3
   203507 2022-23    32.1    11.2
   203507 2023-24    35.2    11.5
   203507 2024-25    34.2    11.8
   203507 2025-26    28.9    10.4

In [84]:
# availability — explicit, so the model stops confusing "hurt" with "declined"
model['GP_rs']  = model['GP_rs'].fillna(0)
model['AVAILABILITY'] = model['GP_rs'] / 82.0                 # share of season played
model['TOTAL_MIN_rs'] = model['MIN_rs'] * model['GP_rs']      # volume: high only if good AND available

In [105]:
# the spine to lag — production identity, not all 1000 cols
SPINE = ['MIN_rs','FGM_rs','FTM_rs','PIE_rs','USG_PCT_rs','FRONT_CT_TOUCHES_rs',
         'POST_TOUCHES_rs','CLOSESTDEF_4_6_FGM_rs','GP_rs','TOTAL_MIN_rs',
         'ALLNBA_WT_EVER']
SPINE = [c for c in SPINE if c in model.columns]

# integer season key so shift respects chronological order
model['_yr'] = model['SEASON'].str[:4].astype(int)
model = model.sort_values(['PLAYER_ID','_yr'])

# lag-1 and lag-2: the player's prior-season and two-seasons-ago production
for k in (1, 2):
    lagged = model.groupby('PLAYER_ID')[SPINE].shift(k)
    # only valid if the prior row is the IMMEDIATELY preceding season (no gap)
    prev_yr = model.groupby('PLAYER_ID')['_yr'].shift(k)
    gap_ok  = (model['_yr'] - prev_yr) == k
    lagged  = lagged.where(gap_ok)                      # NaN out skipped/missing seasons
    lagged.columns = [f"{c}_lag{k}" for c in SPINE]
    model = pd.concat([model, lagged], axis=1)

model = model.drop(columns='_yr')

# sanity: Giannis should now carry last year's healthy minutes alongside this year's
print(model[model['PLAYER_NAME'].str.contains('giannis antetokounmpo', case=False, na=False)]
      [['SEASON','MIN_rs','MIN_rs_lag1','GP_rs','GP_rs_lag1']].sort_values('SEASON').to_string(index=False))

 SEASON  MIN_rs  MIN_rs_lag1  MIN_rs_lag1  GP_rs  GP_rs_lag1  GP_rs_lag1
2015-16    35.3          NaN          NaN     80         NaN         NaN
2016-17    35.6         35.3         35.3     80        80.0        80.0
2017-18    36.7         35.6         35.6     75        80.0        80.0
2018-19    32.8         36.7         36.7     72        75.0        75.0
2019-20    30.4         32.8         32.8     63        72.0        72.0
2020-21    33.0         30.4         30.4     61        63.0        63.0
2021-22    32.9         33.0         33.0     67        61.0        61.0
2022-23    32.1         32.9         32.9     63        67.0        67.0
2023-24    35.2         32.1         32.1     73        63.0        63.0
2024-25    34.2         35.2         35.2     67        73.0        73.0
2025-26    28.9         34.2         34.2     36        67.0        67.0

In [120]:
model = model.drop(columns=[c for c in model.columns if '_lag' in c], errors='ignore')  # top of lag cell
model = model.loc[:, ~model.columns.duplicated()]                                         # belt-and-suspenders

In [110]:
model = model.loc[:, ~model.columns.duplicated()]

mdf = model[model['Salary'].notna() & (model['GP_rs'] >= 20) & (model['MIN_rs'] >= 10)].copy()
mdf['pct_cap'] = mdf['Salary'] / mdf['SEASON'].map(SALARY_CAP)
mdf = mdf[mdf['pct_cap'].notna()].copy()

# does the credential separate the pay tiers the way we expect?
# print(mdf.groupby(mdf['ALLNBA_PRIOR3'].clip(upper=3))['pct_cap'].agg(['mean','count']))
print("mdf:", mdf.shape)
print(mdf['pct_cap'].describe())

mdf: (4228, 1501)
count    4228.000000
mean        0.081441
std         0.084130
min         0.000047
25%         0.018757
50%         0.046164
75%         0.116588
max         0.407253
Name: pct_cap, dtype: float64

In [107]:
# 3) CONFIRM they're present before training
print([c for c in ['AVAILABILITY','TOTAL_MIN_rs'] if c in mdf.columns], "→ should list both")

['AVAILABILITY', 'TOTAL_MIN_rs'] → should list both

In [109]:
print([c for c in model.columns if c.endswith('_lag1')][:15])

['MIN_rs_lag1', 'FGM_rs_lag1', 'FTM_rs_lag1', 'PIE_rs_lag1', 'USG_PCT_rs_lag1', 'FRONT_CT_TOUCHES_rs_lag1', 'POST_TOUCHES_rs_lag1', 'CLOSESTDEF_4_6_FGM_rs_lag1', 'GP_rs_lag1', 'TOTAL_MIN_rs_lag1', 'ALLNBA_WT_EVER_lag1', 'MIN_rs_lag1', 'FGM_rs_lag1', 'FTM_rs_lag1', 'PIE_rs_lag1']

In [20]:
mdf.to_parquet("data/transposed_df_master_with_bio.parquet")
# model = pd.read_parquet("data/transposed_df_master_with_bio.parquet")

# Feature Selection

In [112]:

# 4) re-prefilter (regenerates keep WITH the new cols) then retrain
keep, report = prefilter_features(mdf); print(report)
feats = keep + [c for c in ['AVAILABILITY','TOTAL_MIN_rs'] if c not in keep]
print("availability in feats?", 'AVAILABILITY' in feats, '| total_min in feats?', 'TOTAL_MIN_rs' in feats)

{'start': 1487, 'const': 1, 'empty': 2, 'collinear': 449, 'keep': 1035}
availability in feats? True | total_min in feats? True

In [133]:
feats.remove('DRAFT_YR')   # not a real feature, just a proxy for experience

In [134]:
print("draft year in feats?", 'DRAFT_YR' in feats)

draft year in feats? False

In [135]:

train = mdf[mdf['SEASON'] <= '2021-22']
valid = mdf[mdf['SEASON'] == '2022-23']
test  = mdf[mdf['SEASON'] >= '2023-24']

m_lgb = lgb.LGBMRegressor(
    n_estimators=3000, learning_rate=0.02, num_leaves=31, min_child_samples=30,
    subsample=0.8, subsample_freq=1, colsample_bytree=0.6, reg_lambda=1.0,
    random_state=42, n_jobs=-1)
m_lgb.fit(train[feats], train['pct_cap'],
          eval_set=[(valid[feats], valid['pct_cap'])],
          callbacks=[lgb.early_stopping(150), lgb.log_evaluation(0)])

pred = m_lgb.predict(test[feats])
mae  = mean_absolute_error(test['pct_cap'], pred)
print(f"test R2: {r2_score(test['pct_cap'], pred):.3f}  MAE: {mae:.4f}  (~${mae*SALARY_CAP['2025-26']:,.0f})")

imp = pd.Series(m_lgb.booster_.feature_importance(importance_type='gain'),
                index=feats).sort_values(ascending=False)
print(f"\n>0 gain: {(imp>0).sum()}/{len(feats)}")
print(imp.head(15))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.025922 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 144567
[LightGBM] [Info] Number of data points in the train set: 2673, number of used features: 1036
[LightGBM] [Info] Start training from score 0.079533
Training until validation scores don't improve for 150 rounds
Early stopping, best iteration is:
[488]	valid_0's l2: 0.00123019
test R2: 0.845  MAE: 0.0241  (~$3,733,127)

>0 gain: 979/1036
EXPERIENCE                  69.029709
MIN_rs                      44.010718
MIN_rs_lag1                 27.761961
FGM_rs_lag1                 23.135948
FGM_rs                      15.699504
FRONT_CT_TOUCHES_rs         11.055699
FGM_rs_lag2                 10.394628
MAX_PCT_ELIGIBLE             8.596923
MIN_rs_lag2                  7.346694
ALLNBA_PRIOR_EVER            5.486394
FTM_rs_lag1                  5.306457
DRAFT_POSITION               5.069300
PIE_rs_lag1                  4.935127
FRONT_CT_TOUCHES_rs_lag1     4.204022
OPP_PTS_OFF_TOV_rs           4.155393
dtype: float64

In [136]:
expl   = shap.TreeExplainer(m_lgb)
Xall   = mdf[feats]
sv     = expl.shap_values(Xall)                       # (n_rows, n_feats)

# --- global: mean |SHAP| — the honest importance ranking ---
glob = (pd.Series(np.abs(sv).mean(0), index=feats)
          .sort_values(ascending=False))
print("top 50 by mean |SHAP|:"); print(glob.head(50))

top 50 by mean |SHAP|:
EXPERIENCE                         0.024579
MIN_rs                             0.010397
MIN_rs_lag1                        0.006075
DRAFT_POSITION                     0.003988
MAX_PCT_ELIGIBLE                   0.003847
MIN_rs_lag2                        0.003752
FRONT_CT_TOUCHES_rs                0.003691
FGM_rs_lag1                        0.003268
FGM_rs                             0.002727
CLOSESTDEF_4_6_FGM_rs_lag2         0.002002
FGM_rs_lag2                        0.001962
FRONT_CT_TOUCHES_rs_lag1           0.001842
PIE_rs_lag1                        0.001618
TOTAL_MIN_rs_lag2                  0.001469
OPP_PTS_OFF_TOV_rs                 0.001449
FRONT_CT_TOUCHES_rs_lag2           0.001423
ALLNBA_PRIOR_EVER                  0.001419
TOTAL_MIN_rs_lag1                  0.001256
FTM_rs_lag2                        0.001134
PIE_rs                             0.001107
POST_TOV_POSS_PCT_rs               0.000801
DRIBB_2_FG_PCT_rs                  0.000796
POST_TOUCHES_rs                    0.000788
CLOSESTDEF_4_6_FGM_rs              0.000676
FTM_rs_lag1                        0.000641
PIE_rs_lag2                        0.000637
FTM_rs                             0.000628
TOUCHES_rs                         0.000585
AST_TO_PASS_PCT_rs                 0.000583
SHOT_FG2M_rs                       0.000582
SC_22_18_FG2A_FREQUENCY_rs         0.000574
SCREEN_ASSISTS_rs                  0.000563
DEFLECTIONS_rs                     0.000525
CLOSESTDEF_6P_FG2_PCT_rs           0.000495
OPP_PTS_FB_rs                      0.000439
DREB_rs                            0.000432
PAINT_TOUCH_AST_PCT_rs             0.000430
PAINT_TOUCH_PASSES_PCT_rs          0.000420
FT_AST_rs                          0.000409
USG_PCT_rs_lag2                    0.000405
DRIBB_0_FG3A_FREQUENCY_rs          0.000400
CLUTCH_E_PACE_rs                   0.000365
POST_SF_POSS_PCT_rs                0.000360
CLOSESTDEF_0_2_FGA_FREQUENCY_rs    0.000357
DEFGT15_FGM_GT_15_rs               0.000353
CLOSESTDEF_4_6_FGM_rs_lag1         0.000350
D_FGM_rs                           0.000344
RM_POSS_PCT_rs                     0.000344
CLUTCH_REB_rs                      0.000340
DD2_rs                             0.000336
dtype: float64

In [137]:
mdf = mdf.copy()
mdf['pred_pct_cap'] = m_lgb.predict(Xall)
mdf['residual']     = mdf['pct_cap'] - mdf['pred_pct_cap']   # +overpaid  /  −underpaid
mdf['resid_usd']    = mdf['residual'] * mdf['SEASON'].map(SALARY_CAP)

cols = ['PLAYER_NAME','SEASON','pct_cap','pred_pct_cap','resid_usd']
print("\n💸 most OVERPAID (model says they earn above their profile):")
print(mdf.sort_values('residual', ascending=False)[cols].head(20).to_string(index=False))
print("\n💎 most UNDERPAID:")
print(mdf.sort_values('residual')[cols].head(20).to_string(index=False))

💸 most OVERPAID (model says they earn above their profile):
          PLAYER_NAME  SEASON  pct_cap  pred_pct_cap    resid_usd
            john wall 2022-23 0.330490      0.090359 2.969338e+07
          ben simmons 2024-25 0.279228      0.089309 2.670027e+07
          ben simmons 2022-23 0.286674      0.108548 2.202622e+07
        fred vanvleet 2024-25 0.304767      0.175165 1.822057e+07
       jonathan isaac 2024-25 0.177825      0.049392 1.805604e+07
        fred vanvleet 2023-24 0.300000      0.172597 1.732944e+07
giannis antetokounmpo 2025-26 0.350000      0.225311 1.928280e+07
           kevin love 2022-23 0.221931      0.099116 1.518659e+07
       michael porter 2023-24 0.245454      0.123853 1.654025e+07
          jalen suggs 2025-26 0.226322      0.107274 1.841040e+07
         myles turner 2022-23 0.283608      0.166059 1.453547e+07
           og anunoby 2025-26 0.255866      0.142713 1.749877e+07
    russell westbrook 2022-23 0.374391      0.261810 1.392117e+07
        jaren jackson 2022-23 0.234092      0.122500 1.379881e+07
      khris middleton 2025-26 0.215305      0.105196 1.702799e+07
           og anunoby 2024-25 0.260605      0.151941 1.527689e+07
        klay thompson 2022-23 0.328334      0.220315 1.335702e+07
       michael porter 2022-23 0.250000      0.142410 1.330401e+07
          zach lavine 2025-26 0.307149      0.202567 1.617335e+07
    immanuel quickley 2024-25 0.231172      0.131071 1.407298e+07

💎 most UNDERPAID:
      PLAYER_NAME  SEASON  pct_cap  pred_pct_cap     resid_usd
russell westbrook 2025-26 0.014848      0.150191 -2.093032e+07
  dennis schroder 2022-23 0.014848      0.148739 -1.655627e+07
russell westbrook 2024-25 0.023500      0.147587 -1.744525e+07
    miles bridges 2023-24 0.058236      0.181510 -1.676788e+07
     kevin porter 2025-26 0.033198      0.154078 -1.869378e+07
    demar derozan 2024-25 0.166444      0.285005 -1.666827e+07
      ivica zubac 2024-25 0.083529      0.196131 -1.583050e+07
      kelly oubre 2024-25 0.056783      0.168766 -1.574353e+07
       gary trent 2024-25 0.014848      0.126483 -1.569448e+07
      kelly oubre 2023-24 0.014848      0.125500 -1.505092e+07
       cam thomas 2025-26 0.044215      0.151389 -1.657414e+07
 d'angelo russell 2023-24 0.127243      0.230358 -1.402583e+07
       saddiq bey 2025-26 0.039565      0.142550 -1.592636e+07
  dejounte murray 2023-24 0.133906      0.236833 -1.400021e+07
russell westbrook 2023-24 0.028200      0.130813 -1.395764e+07
    julius randle 2022-23 0.192148      0.291919 -1.233730e+07
spencer dinwiddie 2024-25 0.014848      0.112084 -1.367020e+07
    julius randle 2025-26 0.199578      0.293032 -1.445238e+07
       tyus jones 2024-25 0.014848      0.107072 -1.296557e+07
    demar derozan 2023-24 0.210262      0.301975 -1.247493e+07

In [141]:
this_yr = mdf[mdf['SEASON'] == '2025-26'].copy()
print("most overpaid 2025-26:")
print(this_yr.sort_values('residual', ascending=False)[cols].head(60).to_string(index=False))
print("\nmost underpaid 2025-26:")
print(this_yr.sort_values('residual')[cols].head(60).to_string(index=False))

most overpaid 2025-26:
             PLAYER_NAME  SEASON  pct_cap  pred_pct_cap    resid_usd
   giannis antetokounmpo 2025-26 0.350000      0.225311 1.928280e+07
             jalen suggs 2025-26 0.226322      0.107274 1.841040e+07
              og anunoby 2025-26 0.255866      0.142713 1.749877e+07
         khris middleton 2025-26 0.215305      0.105196 1.702799e+07
             zach lavine 2025-26 0.307149      0.202567 1.617335e+07
           anthony davis 2025-26 0.350000      0.263650 1.335374e+07
         zion williamson 2025-26 0.255072      0.170274 1.311371e+07
          darius garland 2025-26 0.255072      0.171653 1.290043e+07
             evan mobley 2025-26 0.300000      0.219750 1.241043e+07
            jordan poole 2025-26 0.205941      0.128502 1.197573e+07
               ja morant 2025-26 0.255072      0.179120 1.174579e+07
             alex caruso 2025-26 0.117054      0.045152 1.111934e+07
                naz reid 2025-26 0.139361      0.075880 9.817081e+06
           stephen curry 2025-26 0.385438      0.322415 9.746262e+06
            jimmy butler 2025-26 0.350000      0.287145 9.720380e+06
         lauri markkanen 2025-26 0.300000      0.237960 9.594333e+06
       immanuel quickley 2025-26 0.210156      0.149647 9.357562e+06
           luguentz dort 2025-26 0.117831      0.057776 9.287331e+06
            franz wagner 2025-26 0.250000      0.191538 9.040921e+06
      isaiah hartenstein 2025-26 0.184291      0.126547 8.929849e+06
      karl-anthony towns 2025-26 0.343636      0.287278 8.715523e+06
            john collins 2025-26 0.171875      0.116029 8.636507e+06
         andrew nembhard 2025-26 0.117054      0.061653 8.567556e+06
           deandre ayton 2025-26 0.217623      0.162627 8.505040e+06
          jonathan isaac 2025-26 0.096995      0.043702 8.241576e+06
             lamelo ball 2025-26 0.245454      0.194712 7.847107e+06
             paul george 2025-26 0.334090      0.284414 7.682264e+06
       jarred vanderbilt 2025-26 0.074825      0.027594 7.304152e+06
         cade cunningham 2025-26 0.300000      0.252943 7.277196e+06
             joel embiid 2025-26 0.357101      0.310806 7.159344e+06
            jerami grant 2025-26 0.206923      0.160802 7.132500e+06
            devin booker 2025-26 0.343636      0.297574 7.123377e+06
             jalen green 2025-26 0.217169      0.173036 6.824932e+06
            gabe vincent 2025-26 0.074363      0.031178 6.678464e+06
             maxi kleber 2025-26 0.071130      0.028020 6.666733e+06
           kevin huerter 2025-26 0.116336      0.073312 6.653609e+06
            jaylen brown 2025-26 0.343636      0.301026 6.589571e+06
      zaccharie risacher 2025-26 0.085341      0.043657 6.446303e+06
        patrick williams 2025-26 0.116394      0.074897 6.417326e+06
         jaden mcdaniels 2025-26 0.157734      0.116427 6.388008e+06
          michael porter 2025-26 0.247875      0.209764 5.893637e+06
            terance mann 2025-26 0.100228      0.062280 5.868649e+06
         anthony edwards 2025-26 0.294545      0.258137 5.630350e+06
         robert williams 2025-26 0.085910      0.049663 5.605446e+06
            desmond bane 2025-26 0.237481      0.201406 5.578811e+06
     dorian finney-smith 2025-26 0.082123      0.046450 5.516711e+06
           tobias harris 2025-26 0.172225      0.138146 5.270236e+06
            jamal murray 2025-26 0.300000      0.265983 5.260669e+06
              isaiah joe 2025-26 0.079939      0.046699 5.140511e+06
         duncan robinson 2025-26 0.108859      0.075788 5.114374e+06
kentavious caldwell-pope 2025-26 0.139812      0.106765 5.110651e+06
          draymond green 2025-26 0.167432      0.137623 4.609816e+06
        matisse thybulle 2025-26 0.074686      0.045457 4.520239e+06
          keldon johnson 2025-26 0.113161      0.084099 4.494317e+06
            dylan harper 2025-26 0.079991      0.051017 4.480623e+06
         jaylin williams 2025-26 0.054645      0.027431 4.208536e+06
         harrison barnes 2025-26 0.122860      0.096834 4.024926e+06
            nikola jokic 2025-26 0.357101      0.331621 3.940354e+06
            kevin durant 2025-26 0.353764      0.328532 3.902050e+06
          isaiah stewart 2025-26 0.096995      0.072120 3.846927e+06

most underpaid 2025-26:
            PLAYER_NAME  SEASON  pct_cap  pred_pct_cap     resid_usd
      russell westbrook 2025-26 0.014848      0.150191 -2.093032e+07
           kevin porter 2025-26 0.033198      0.154078 -1.869378e+07
             cam thomas 2025-26 0.044215      0.151389 -1.657414e+07
             saddiq bey 2025-26 0.039565      0.142550 -1.592636e+07
          julius randle 2025-26 0.199578      0.293032 -1.445238e+07
       payton pritchard 2025-26 0.046765      0.137346 -1.400798e+07
            deni avdija 2025-26 0.092954      0.180442 -1.352986e+07
       d'angelo russell 2025-26 0.036761      0.116661 -1.235624e+07
         taurean prince 2025-26 0.021363      0.098828 -1.197969e+07
            kelly oubre 2025-26 0.054202      0.131228 -1.191181e+07
          killian hayes 2025-26 0.001707      0.077917 -1.178572e+07
         nikola vucevic 2025-26 0.138907      0.211029 -1.115358e+07
          demar derozan 2025-26 0.158878      0.229862 -1.097750e+07
             al horford 2025-26 0.036761      0.106919 -1.084971e+07
            ivica zubac 2025-26 0.122175      0.192214 -1.083130e+07
           tim hardaway 2025-26 0.014848      0.083143 -1.056150e+07
           james harden 2025-26 0.253369      0.311793 -9.035124e+06
            brook lopez 2025-26 0.056580      0.114734 -8.993224e+06
     guerschon yabusele 2025-26 0.035565      0.093116 -8.900104e+06
          mikal bridges 2025-26 0.161012      0.218142 -8.834972e+06
         wendell carter 2025-26 0.070160      0.126514 -8.715066e+06
              josh hart 2025-26 0.125914      0.179549 -8.294481e+06
          nick richards 2025-26 0.032332      0.085927 -8.288401e+06
          pj washington 2025-26 0.091513      0.144629 -8.214292e+06
          jalen brunson 2025-26 0.225960      0.278868 -8.182097e+06
            bruce brown 2025-26 0.014848      0.066758 -8.027580e+06
      de'anthony melton 2025-26 0.019922      0.071411 -7.962540e+06
             coby white 2025-26 0.083344      0.134028 -7.838114e+06
             gary trent 2025-26 0.023907      0.074092 -7.761076e+06
          cameron payne 2025-26 0.004608      0.054654 -7.739491e+06
            ayo dosunmu 2025-26 0.048617      0.096834 -7.456554e+06
          miles bridges 2025-26 0.161658      0.209830 -7.449601e+06
          neemias queta 2025-26 0.015193      0.063161 -7.418119e+06
 jeremiah robinson-earl 2025-26 0.000853      0.046100 -6.997202e+06
       collin gillespie 2025-26 0.014848      0.059224 -6.862476e+06
         onyeka okongwu 2025-26 0.096995      0.138192 -6.371010e+06
             tyus jones 2025-26 0.045264      0.086344 -6.352868e+06
           bobby portis 2025-26 0.086945      0.127709 -6.304096e+06
       donte divincenzo 2025-26 0.077531      0.115445 -5.863171e+06
       precious achiuwa 2025-26 0.013654      0.051559 -5.861918e+06
             rj barrett 2025-26 0.179152      0.216530 -5.780288e+06
          miles mcbride 2025-26 0.028021      0.064784 -5.685321e+06
         jalen williams 2025-26 0.042555      0.078081 -5.494062e+06
shai gilgeous-alexander 2025-26 0.247875      0.281395 -5.183778e+06
      julian champagnie 2025-26 0.019399      0.052332 -5.093062e+06
      victor wembanyama 2025-26 0.086499      0.119369 -5.083181e+06
           de'aaron fox 2025-26 0.239879      0.272733 -5.080755e+06
          marvin bagley 2025-26 0.014848      0.047434 -5.039259e+06
         quentin grimes 2025-26 0.056524      0.089001 -5.022603e+06
         keyonte george 2025-26 0.027669      0.059576 -4.934224e+06
          jarrett allen 2025-26 0.129327      0.160844 -4.874088e+06
         toumani camara 2025-26 0.014366      0.044803 -4.706980e+06
          aaron nesmith 2025-26 0.071130      0.100922 -4.607314e+06
        dennis schroder 2025-26 0.091201      0.119933 -4.443222e+06
         andre drummond 2025-26 0.032332      0.061055 -4.441955e+06
          dillon brooks 2025-26 0.136596      0.164679 -4.342958e+06
            mike conley 2025-26 0.074362      0.102147 -4.296926e+06
          javonte green 2025-26 0.014848      0.042326 -4.249361e+06
         grant williams 2025-26 0.088236      0.115456 -4.209379e+06
         brandon miller 2025-26 0.077394      0.104567 -4.202129e+06

In [96]:
# reuse the explainer + shap values from the global cell (don't recompute)
# sv, expl, Xall, feats, mdf all already exist

def explain_player(name, season, top_n=20):
    row = mdf[(mdf['PLAYER_NAME'] == name) & (mdf['SEASON'] == season)]
    if row.empty:
        print(f"no row for {name} {season}"); return
    i   = mdf.index.get_loc(row.index[0])
    cap = SALARY_CAP[season]

    contrib = pd.Series(sv[i], index=feats)
    top = contrib.reindex(contrib.abs().sort_values(ascending=False).index).head(top_n)

    base = expl.expected_value
    pred = row['pred_pct_cap'].iloc[0]; actual = row['pct_cap'].iloc[0]
    print(f"\n{name} — {season}")
    print(f"  market baseline:  {base:6.1%}  (${base*cap:,.0f})")
    print(f"  model prediction: {pred:6.1%}  (${pred*cap:,.0f})")
    print(f"  actual salary:    {actual:6.1%}  (${actual*cap:,.0f})")
    print(f"  → {'OVER' if actual>pred else 'UNDER'}paid vs market by ${abs(actual-pred)*cap:,.0f}\n")
    print("  what pushed the market price (+ up / − down):")
    for f, v in top.items():
        print(f"    {'+' if v>0 else '−'} {f:32s} {v*cap:>+12,.0f}")

# the players you just flagged
explain_player("giannis antetokounmpo", "2025-26")
explain_player("cj mccollum", "2025-26")
explain_player("julius randle", "2025-26")
explain_player("stephen curry", "2025-26")
explain_player("lebron james", "2025-26")
explain_player("joel embiid", "2025-26")

giannis antetokounmpo — 2025-26
  market baseline:    7.9%  ($12,291,686)
  model prediction:  20.4%  ($31,555,975)
  actual salary:     35.0%  ($54,126,450)
  → OVERpaid vs market by $22,570,475

  what pushed the market price (+ up / − down):
    + EXPERIENCE                         +6,431,776
    + FGM_rs                             +3,571,216
    + ALLNBA_PRIOR_EVER                  +2,306,929
    + FRONT_CT_TOUCHES_rs                +2,240,844
    − MIN_rs                             -1,561,650
    + POST_TOUCHES_rs                    +1,143,260
    + MAX_PCT_ELIGIBLE                   +1,077,006
    + OPP_PTS_OFF_TOV_rs                   +665,455
    + ALLNBA_PRIOR3                        +610,843
    + FTM_rs                               +568,524
    + POST_POSS_rs                         +523,003
    − DRAFT_POSITION                       -513,331
    + DRAFT_YR                             +434,371
    − DRIBB_2_FG_PCT_rs                    -425,867
    + REB_CHANCE_PCT_rs                    +300,431
    + DREB_rs                              +259,085
    + L_rs                                 +248,780
    + PIE_rs                               +237,449
    − ISO_POSS_PCT_rs                      -227,110
    + PCT_BOX_OUTS_OFF_rs                  +218,957

cj mccollum — 2025-26
  market baseline:    7.9%  ($12,291,686)
  model prediction:  21.8%  ($33,764,757)
  actual salary:     19.8%  ($30,666,666)
  → UNDERpaid vs market by $3,098,091

  what pushed the market price (+ up / − down):
    + EXPERIENCE                         +6,603,590
    + MIN_rs                             +3,734,636
    + FGM_rs                             +2,622,373
    + MAX_PCT_ELIGIBLE                     +965,314
    + OPP_PTS_OFF_TOV_rs                   +844,957
    + CLOSESTDEF_4_6_FGM_rs                +756,725
    + CLUTCH_BLK_po                        +673,896
    + DRAFT_YR                             +642,274
    + FRONT_CT_TOUCHES_rs                  +511,120
    − ALLNBA_PRIOR_EVER                    -441,536
    + DRAFT_POSITION                       +438,670
    + Mid_Range_FGM_po                     +263,529
    + DEF2_NS_FG2_PCT_rs                   +255,590
    − POST_TOUCHES_rs                      -244,321
    + CLOSESTDEF_4_6_FG2M_po               +210,758
    + OFFSCREEN_POSS_rs                    +201,844
    + CLOSESTDEF_4_6_FGM_po                +196,260
    + AST_TO_PASS_PCT_rs                   +193,550
    + CLOSESTDEF_4_6_FGA_po                +193,550
    + PCT_AST_3PM_rs                       +177,924

julius randle — 2025-26
  market baseline:    7.9%  ($12,291,686)
  model prediction:  25.8%  ($39,821,797)
  actual salary:     20.0%  ($30,864,198)
  → UNDERpaid vs market by $8,957,599

  what pushed the market price (+ up / − down):
    + EXPERIENCE                         +7,681,144
    + MIN_rs                             +7,527,764
    + FGM_rs                             +3,265,363
    + FRONT_CT_TOUCHES_rs                +1,825,079
    + ALLNBA_PRIOR_EVER                  +1,577,631
    + MAX_PCT_ELIGIBLE                   +1,220,714
    + POST_TOUCHES_rs                      +840,122
    − DRAFT_YR                             -799,996
    + OPP_PTS_OFF_TOV_rs                   +587,909
    + CLOSESTDEF_4_6_FGM_rs                +580,646
    + ALLNBA_PRIOR3                        +496,180
    + FTM_rs                               +473,105
    + PIE_rs                               +438,642
    + DRAFT_POSITION                       +414,626
    + AVG_SPEED_DEF_rs                     +352,919
    + AST_TO_PASS_PCT_rs                   +315,716
    + PCT_BOX_OUTS_TEAM_REB_rs             +214,714
    − CLOSESTDEF_4_6_FG2_PCT_po            -211,667
    + CLOSESTDEF_0_2_FGA_FREQUENCY_rs      +205,811
    − PAINT_TOUCH_FOULS_PCT_rs             -182,132

stephen curry — 2025-26
  market baseline:    7.9%  ($12,291,686)
  model prediction:  31.5%  ($48,752,342)
  actual salary:     38.5%  ($59,606,817)
  → OVERpaid vs market by $10,854,475

  what pushed the market price (+ up / − down):
    + EXPERIENCE                         +7,358,674
    + MIN_rs                             +6,675,643
    + ALLNBA_PRIOR_EVER                  +3,732,322
    + FGM_rs                             +3,697,736
    + DRAFT_YR                           +1,370,705
    + FRONT_CT_TOUCHES_rs                +1,321,413
    + ALLNBA_PRIOR3                      +1,226,831
    + CLOSESTDEF_4_6_FGM_rs              +1,114,844
    + MAX_PCT_ELIGIBLE                   +1,013,949
    + DRAFT_POSITION                       +970,947
    + OPP_PTS_OFF_TOV_rs                   +732,512
    + FTM_rs                               +657,717
    + PIE_rs                               +531,065
    + FT_AST_rs                            +439,037
    + PCT_BOX_OUTS_TEAM_REB_rs             +357,487
    + AST_TO_PASS_PCT_rs                   +355,392
    + CLOSESTDEF_0_2_FGA_FREQUENCY_rs      +343,078
    + SC_18_15_FG3M_rs                     +286,145
    − SC_7_4_EFG_PCT_rs                    -263,330
    − Mid_Range_FG_PCT_rs                  -258,862

lebron james — 2025-26
  market baseline:    7.9%  ($12,291,686)
  model prediction:  33.6%  ($51,957,326)
  actual salary:     34.0%  ($52,627,153)
  → OVERpaid vs market by $669,827

  what pushed the market price (+ up / − down):
    + MIN_rs                             +8,306,558
    + EXPERIENCE                         +8,004,025
    + FGM_rs                             +3,869,520
    + ALLNBA_PRIOR_EVER                  +3,132,813
    + DRAFT_POSITION                     +2,045,421
    + FRONT_CT_TOUCHES_rs                +1,757,574
    + MAX_PCT_ELIGIBLE                   +1,330,075
    − AVG_SPEED_OFF_rs                   -1,085,943
    + DRAFT_YR                             +999,171
    + OPP_PTS_OFF_TOV_rs                   +740,449
    + FTM_rs                               +735,722
    + ALLNBA_PRIOR3                        +726,209
    + POST_TOUCHES_rs                      +680,494
    + PIE_rs                               +676,876
    + CLOSESTDEF_4_6_FGM_rs                +656,937
    + FT_AST_rs                            +620,168
    + CLOSESTDEF_0_2_FGA_FREQUENCY_rs      +302,583
    + AST_TO_PASS_PCT_rs                   +262,474
    + SC_7_4_FGA_rs                        +258,785
    + POST_POSS_rs                         +250,942

joel embiid — 2025-26
  market baseline:    7.9%  ($12,291,686)
  model prediction:  30.1%  ($46,492,808)
  actual salary:     35.7%  ($55,224,526)
  → OVERpaid vs market by $8,731,718

  what pushed the market price (+ up / − down):
    + MIN_rs                             +7,667,417
    + EXPERIENCE                         +7,483,047
    + FGM_rs                             +3,556,542
    + ALLNBA_PRIOR_EVER                  +2,757,110
    + DRAFT_POSITION                     +1,885,263
    + FRONT_CT_TOUCHES_rs                +1,843,222
    + MAX_PCT_ELIGIBLE                   +1,184,011
    + CLOSESTDEF_4_6_FGM_rs                +940,267
    − AVG_SPEED_OFF_rs                     -881,722
    − DRAFT_YR                             -663,572
    + PIE_rs                               +623,061
    + FT_AST_rs                            +488,595
    + POST_TOUCHES_rs                      +467,777
    + ALLNBA_PRIOR3                        +466,875
    + FTM_rs                               +452,351
    − SC_22_18_FGA_FREQUENCY_rs            -356,911
    + AVG_SPEED_DEF_rs                     +311,691
    + CLOSESTDEF_0_2_FGA_FREQUENCY_rs      +278,981
    + DEF_RIM_FGM_po                       +278,034
    + L_rs                                 +239,223

In [143]:
ranked = (mdf[mdf['SEASON']=='2025-26']
          .assign(deserved_usd = mdf['pred_pct_cap']*SALARY_CAP['2025-26'])
          .sort_values('pred_pct_cap', ascending=False)
          [['PLAYER_NAME','pred_pct_cap','deserved_usd','pct_cap','resid_usd']])
print(ranked.head(70).to_string(index=False))

            PLAYER_NAME  pred_pct_cap  deserved_usd  pct_cap     resid_usd
           lebron james      0.341513  5.281396e+07 0.340305 -1.868069e+05
          kawhi leonard      0.334501  5.172955e+07 0.323317 -1.729551e+06
           nikola jokic      0.331621  5.128417e+07 0.357101  3.940354e+06
           kevin durant      0.328532  5.080656e+07 0.353764  3.902050e+06
          stephen curry      0.322415  4.986055e+07 0.385438  9.746262e+06
            luka doncic      0.317096  4.903801e+07 0.297449 -3.038355e+06
           james harden      0.311793  4.821782e+07 0.253369 -9.035124e+06
            joel embiid      0.310806  4.806518e+07 0.357101  7.159344e+06
           jaylen brown      0.301026  4.655269e+07 0.343636  6.589571e+06
           devin booker      0.297574  4.601889e+07 0.343636  7.123377e+06
          julius randle      0.293032  4.531658e+07 0.199578 -1.445238e+07
       donovan mitchell      0.290166  4.487331e+07 0.300000  1.520792e+06
     karl-anthony towns      0.287278  4.442674e+07 0.343636  8.715523e+06
           jimmy butler      0.287145  4.440607e+07 0.350000  9.720380e+06
            paul george      0.284414  4.398383e+07 0.334090  7.682264e+06
shai gilgeous-alexander      0.281395  4.351683e+07 0.247875 -5.183778e+06
          pascal siakam      0.281280  4.349907e+07 0.294545  2.051446e+06
          jalen brunson      0.278868  4.312610e+07 0.225960 -8.182097e+06
           de'aaron fox      0.272733  4.217737e+07 0.239879 -5.080755e+06
         brandon ingram      0.269961  4.174870e+07 0.246337 -3.653465e+06
           jamal murray      0.265983  4.113343e+07 0.300000  5.260669e+06
          anthony davis      0.263650  4.077271e+07 0.350000  1.335374e+07
        anthony edwards      0.258137  3.992016e+07 0.294545  5.630350e+06
            bam adebayo      0.255891  3.957283e+07 0.239879 -2.476208e+06
        cade cunningham      0.252943  3.911690e+07 0.300000  7.277196e+06
         scottie barnes      0.251706  3.892553e+07 0.250000 -2.637764e+05
        lauri markkanen      0.237960  3.679977e+07 0.300000  9.594333e+06
         alperen sengun      0.236530  3.657859e+07 0.219500 -2.633639e+06
           tyrese maxey      0.236416  3.656104e+07 0.245454  1.397723e+06
          demar derozan      0.229862  3.554750e+07 0.158878 -1.097750e+07
  giannis antetokounmpo      0.225311  3.484365e+07 0.350000  1.928280e+07
            rudy gobert      0.225275  3.483807e+07 0.226322  1.619260e+05
            evan mobley      0.219750  3.398367e+07 0.300000  1.241043e+07
          mikal bridges      0.218142  3.373497e+07 0.161012 -8.834972e+06
             rj barrett      0.216530  3.348565e+07 0.179152 -5.780288e+06
            cj mccollum      0.214746  3.320988e+07 0.198301 -2.543211e+06
          jalen johnson      0.212967  3.293473e+07 0.193990 -2.934731e+06
         nikola vucevic      0.211029  3.263506e+07 0.138907 -1.115358e+07
          jaren jackson      0.210533  3.255824e+07 0.226322  2.441756e+06
          miles bridges      0.209830  3.244960e+07 0.161658 -7.449601e+06
         michael porter      0.209764  3.243941e+07 0.247875  5.893637e+06
            zach lavine      0.202567  3.132631e+07 0.307149  1.617335e+07
           desmond bane      0.201406  3.114686e+07 0.237481  5.578811e+06
            tyler herro      0.201349  3.113809e+07 0.200457 -1.380917e+05
            lamelo ball      0.194712  3.011165e+07 0.245454  7.847107e+06
            ivica zubac      0.192214  2.972528e+07 0.122175 -1.083130e+07
           franz wagner      0.191538  2.962083e+07 0.250000  9.040921e+06
          devin vassell      0.190453  2.945297e+07 0.174591 -2.452970e+06
     kristaps porzingis      0.187429  2.898528e+07 0.198722  1.746424e+06
           jrue holiday      0.185744  2.872478e+07 0.209509  3.675222e+06
            deni avdija      0.180442  2.790486e+07 0.092954 -1.352986e+07
              josh hart      0.179549  2.776672e+07 0.125914 -8.294481e+06
              ja morant      0.179120  2.770030e+07 0.255072  1.174579e+07
          derrick white      0.178570  2.761539e+07 0.181704  4.846129e+05
            jalen green      0.173036  2.675957e+07 0.217169  6.824932e+06
         darius garland      0.171653  2.654566e+07 0.255072  1.290043e+07
        anfernee simons      0.170379  2.634863e+07 0.178979  1.329940e+06
        zion williamson      0.170274  2.633238e+07 0.255072  1.311371e+07
          dillon brooks      0.164679  2.546707e+07 0.136596 -4.342958e+06
          deandre ayton      0.162627  2.514977e+07 0.217623  8.505040e+06
         andrew wiggins      0.161569  2.498620e+07 0.182501  3.237016e+06
          jarrett allen      0.160844  2.487409e+07 0.129327 -4.874088e+06
           jerami grant      0.160802  2.486750e+07 0.206923  7.132500e+06
            trey murphy      0.155679  2.407521e+07 0.161658  9.247864e+05
            josh giddey      0.155559  2.405678e+07 0.161658  9.432187e+05
           kevin porter      0.154078  2.382778e+07 0.033198 -1.869378e+07
          norman powell      0.153728  2.377353e+07 0.132448 -3.290774e+06
             cam thomas      0.151389  2.341192e+07 0.044215 -1.657414e+07
           aaron gordon      0.151172  2.337823e+07 0.147701 -5.367723e+05
      russell westbrook      0.150191  2.322659e+07 0.014848 -2.093032e+07

# Save Model

In [126]:
# clean model (idempotent guard for any future lag re-runs)
model = model.loc[:, ~model.columns.duplicated()]

# 1) the trained model — both formats
m_lgb.booster_.save_model("data/salary_model_v1.txt")
joblib.dump(m_lgb, "data/salary_model_v1.pkl")

# 2) the exact feature list + order (model is useless without this)
json.dump(feats, open("data/feats_v1.json", "w"))

# 3) the residual table — the product, queryable
out_cols = ['PLAYER_NAME','SEASON','pct_cap','pred_pct_cap','resid_usd']
mdf[out_cols].to_parquet("data/residuals_v1.parquet")

# 4) the scoreable population (everyone, not just training rows) for the app
mdf.to_parquet("data/mdf_v1.parquet")

print("saved:", report)   # log the prefilter summary so you know what built this
print(f"R2 0.847 | MAE $3.75M | {len(feats)} features | {len(mdf)} rows")

saved: {'start': 1487, 'const': 1, 'empty': 2, 'collinear': 449, 'keep': 1035}
R2 0.847 | MAE $3.75M | 1037 features | 4228 rows

# Streamlit App

In [127]:
# global ranking → the features worth storing for the app
glob = pd.Series(np.abs(sv).mean(0), index=feats).sort_values(ascending=False)
DISPLAY_FEATS = glob.head(25).index.tolist()          # the app shows top contributors per player
display_idx   = [feats.index(f) for f in DISPLAY_FEATS]

# build a long-format SHAP table: one row per (player-season, feature) = easy for plotly
rows = []
cap_by_season = mdf['SEASON'].map(SALARY_CAP).values
for r in range(len(mdf)):
    cap = cap_by_season[r]
    for f, j in zip(DISPLAY_FEATS, display_idx):
        rows.append((mdf['PLAYER_NAME'].iloc[r], mdf['SEASON'].iloc[r],
                     f, sv[r, j], sv[r, j] * cap, mdf[f].iloc[r]))

shap_long = pd.DataFrame(rows, columns=['PLAYER_NAME','SEASON','feature',
                                        'shap','shap_usd','feat_value'])
shap_long.to_parquet("data/shap_v1.parquet")

# also store the per-player baseline + prediction so the waterfall has its anchors
base = float(expl.expected_value)
meta = mdf[['PLAYER_NAME','SEASON','pct_cap','pred_pct_cap','resid_usd']].copy()
meta['baseline_pct'] = base
meta.to_parquet("data/app_meta_v1.parquet")

print(f"stored SHAP for {len(DISPLAY_FEATS)} features × {len(mdf)} player-seasons "
      f"= {len(shap_long):,} rows ({shap_long.memory_usage(deep=True).sum()/1e6:.1f} MB)")
print("baseline pct_cap:", round(base, 4))

stored SHAP for 25 features × 4228 player-seasons = 105,700 rows (24.2 MB)
baseline pct_cap: 0.0796

In [129]:
pip install -r data/requirements.txt

94527.50s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Collecting streamlit>=1.40 (from -r data/requirements.txt (line 1))
  Downloading streamlit-1.50.0-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: pandas>=2.2 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from -r data/requirements.txt (line 2)) (2.3.3)
Collecting plotly>=5.24 (from -r data/requirements.txt (line 3))
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: pyarrow>=15 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from -r data/requirements.txt (line 4)) (21.0.0)
Collecting altair!=5.4.0,!=5.4.1,<6,>=4.0 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading altair-5.5.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<7,>=4.0 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading cachetools-6.2.6-py3-none-any.whl.metadata (5.6 kB)
Collecting click<9,>=7.0 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: numpy<3,>=1.23 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from streamlit>=1.40->-r data/requirements.txt (line 1)) (2.0.2)
Collecting packaging<26,>=20 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pillow<12,>=7.1.0 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from streamlit>=1.40->-r data/requirements.txt (line 1)) (11.3.0)
Collecting protobuf<7,>=3.20 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: requests<3,>=2.27 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from streamlit>=1.40->-r data/requirements.txt (line 1)) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from streamlit>=1.40->-r data/requirements.txt (line 1)) (4.15.0)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from streamlit>=1.40->-r data/requirements.txt (line 1)) (6.5.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from pandas>=2.2->-r data/requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from pandas>=2.2->-r data/requirements.txt (line 2)) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from pandas>=2.2->-r data/requirements.txt (line 2)) (2026.2)
Requirement already satisfied: jinja2 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1)) (3.1.6)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading jsonschema-4.25.1-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=1.14.2 (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading narwhals-2.21.0-py3-none-any.whl.metadata (16 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit>=1.40->-r data/requirements.txt (line 1)) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit>=1.40->-r data/requirements.txt (line 1)) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit>=1.40->-r data/requirements.txt (line 1)) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from requests<3,>=2.27->streamlit>=1.40->-r data/requirements.txt (line 1)) (2026.6.17)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/siddharthravindran/Library/Python/3.9/lib/python/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1)) (3.0.3)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit>=1.40->-r data/requirements.txt (line 1))
  Downloading rpds_py-0.27.1-cp39-cp39-macosx_10_12_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=2.2->-r data/requirements.txt (line 2)) (1.15.0)
Downloading streamlit-1.50.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 37.0 MB/s  0:00:00eta 0:00:01
Downloading altair-5.5.0-py3-none-any.whl (731 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.2/731.2 kB 13.3 MB/s  0:00:00
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-6.2.6-py3-none-any.whl (11 kB)
Downloading click-8.1.8-py3-none-any.whl (98 kB)
Downloading gitpython-3.1.50-py3-none-any.whl (212 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading packaging-25.0-py3-none-any.whl (66 kB)
Downloading protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 49.1 MB/s  0:00:00m0:00:01
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading plotly-6.8.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 41.7 MB/s  0:00:00 eta 0:00:01
Downloading jsonschema-4.25.1-py3-none-any.whl (90 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading narwhals-2.21.0-py3-none-any.whl (451 kB)
Downloading referencing-0.36.2-py3-none-any.whl (26 kB)
Downloading rpds_py-0.27.1-cp39-cp39-macosx_10_12_x86_64.whl (372 kB)
Installing collected packages: toml, tenacity, smmap, rpds-py, protobuf, packaging, narwhals, click, cachetools, blinker, attrs, referencing, pydeck, plotly, gitdb, jsonschema-specifications, gitpython, jsonschema, altair, streamlit
  Attempting uninstall: packaging0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/20 [protobuf]
    Found existing installation: packaging 26.2━━━━━━━━━━━━━━━  4/20 [protobuf]
    Uninstalling packaging-26.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/20 [protobuf]
      Successfully uninstalled packaging-26.2━━━━━━━━━━━━━━━━━  4/20 [protobuf]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20/20 [streamlit]20 [streamlit]]
Successfully installed altair-5.5.0 attrs-26.1.0 blinker-1.9.0 cachetools-6.2.6 click-8.1.8 gitdb-4.0.12 gitpython-3.1.50 jsonschema-4.25.1 jsonschema-specifications-2025.9.1 narwhals-2.21.0 packaging-25.0 plotly-6.8.0 protobuf-6.33.6 pydeck-0.9.2 referencing-0.36.2 rpds-py-0.27.1 smmap-5.0.3 streamlit-1.50.0 tenacity-9.1.2 toml-0.10.2
Note: you may need to restart the kernel to use updated packages.